### ISSUE TITLE
[card] Error if 0%

### ISSUE THREAD

**Issue by annelhote** [dataesr/bso-ui#187]
Je ne peux pas représenter une carte à 0%. Si je veux une carte en pourcentage te que ma valeur à afficher est 0, alors ma carte sera masquée. Pourtant cette information n'est pas forcément un manque de représentation.

**Comment by poplingue** [comment]
Oui, effectivement pas possible une carte à 0. On a le cas ?

**Comment by annelhote** [comment]
Je ne sais pas si on a le cas aujourd'hui mais ce sont des choses qui arrivent ;). Donc toujours mieux de les gérer...
