### ISSUE TITLE
Utiliser des endpoints elastic différents en staging et en prod 

### ISSUE THREAD

**Issue by ericjeangirard** [dataesr/bso-ui#214]
Objectif : quand on met à jour les données, on voudrait d'abord montrer en interne à quoi ca va ressembler avant de changer sur le site public

Pour le moment, on a les deux variables

export const ES_API_URL = 'https://cluster.elasticsearch.dataesr.ovh/bso-publications/_search';
export const ES_STUDIES_API_URL = 'https://cluster.elasticsearch.dataesr.ovh/bso-clinical-trials/_search';

en staging, il faudrait utiliser 
'https://cluster.elasticsearch.dataesr.ovh/bso-publications-staging/_search'
et 'https://cluster.elasticsearch.dataesr.ovh/bso-clinical-trials-staging/_search';

**Comment by annelhote** [comment]
PS: Attention ces indexes n'existent pas encore !

**Comment by annelhote** [comment]
**Staging :**
bso-publications-staging
bso-clinical-trials-staging

**Production :**
bso-publications
bso-clinical-trials
