### ISSUE TITLE
Afficher certains graphes seulement en staging

### ISSUE THREAD

**Issue by ericjeangirard** [dataesr/bso-ui#215]
Objectif : certains graphes reposent sur des données qui ne sont pas encore assez matures, on voudrait pouvoir continuer à en discuter en interne sans les mettre sur le site public

Premier cas que nous avons : le graphe 'publi.publishers.couts-publication.chart-depenses-estimees' (national & santé)

**Comment by annelhote** [comment]
Pour masquer un graphe en production, il faut ajouter l'attribut `isDisplayed={!isInProduction()}` sur le tag `BSOChart`.

**Comment by annelhote** [comment]
https://create-react-app.dev/docs/adding-custom-environment-variables/
