### ISSUE TITLE
les textes des titles et des comments n'interprètent pas le HTML

### ISSUE THREAD

**Issue by ericjeangirard** [dataesr/bso-ui#218]
dans les titres de graphes et dans les commentaires, il serait utile de pouvoir insérer des balises <br/> ou <u> etc ...

**Comment by annelhote** [comment]
Est-ce que le support des sauts de ligne est suffisants ou bien est-ce que d'autres balises seraient utiles ?

**Comment by annelhote** [comment]
Autres balises utiles : souligné et gras.
Pour insérer un saut de ligne, ajouter `<linebreak></linebreak>`.
