### ISSUE TITLE
Glossaire - Coquilles

### ISSUE THREAD

**Issue by Jojooct10** [dataesr/bso-ui#250]
- [x] ANR : ajouter un lien sortant vers ANR
- [x] APC : développer le sigle en anglais. Le lecteur peut se poser la question de ce que cela veut dire et n'a pas la réponse
- [x] ClinicalTrials : ajouter un lien sortant vers ClinicalTrials et lien vers NIH
- [x] DOAJ : lien vers les services qui sont nommés
- [x] Embargo : "l'Etat" ->"l'État"
- [x] "Etude observationnelle"->"Étude observationnelle"
- [x] EU CTR : lien vers le service
- [x] "Centre pour la Communication Scientifique Directe"->"Centre pour la Communication Scientifique Directe" (Cf. le site du CCSD)
- [x] " scientifique (exemple: Creative Commons)." ->" scientifique (exemple : Creative Commons)."
- [x] Liste de Beal : faut laisser cette entrée dans le Glossaire dans la mesure où, de mémoire, on a supprimé le graph associé (idem sur dernière entrée du glossaire)
- [x] loi pour une république numérique : ajouter un lien vers https://www.legifrance.gouv.fr/dossierlegislatif/JORFDOLE000031589829/
- [x] OpenAPC : lien vers OpenAPC
- [x] OGP : 78 pays (cf. https://www.opengovpartnership.org/fr/about/approach/)
- [x] PubMed : lien vers PubMed

**Comment by annelhote** [comment]
* On mentionne toujours la liste de Beall dans notre commentaire : https://bso.staging.dataesr.ovh/publications/editeurs?id=publishers.poids-revues, donc je propose de laisser cette entrée du glossaire.
* Il en va de même pour l'autre entrée incriminée.
