### ISSUE TITLE
Page d'accueil générale - BSO

### ISSUE THREAD

**Issue by Jojooct10** [dataesr/bso-ui#252]
- [x] "dont l'un des auteurs au moins est affilié à un établissement de l'enseignement supérieur et de la recherche en France." La formulation semble exclure les publication avec affiliation d'une entreprise ou autre. Je sais presque à chaque fois il y a un auteur de l'ESR mais pas forcément tout le temps non plus. Ou, tout au moins, nous ne sommes pas capables de prouver cette assertion
- [x] Card avec augmentation : pourquoi écrit on "pts" et pas "points"
- [x] Le partage linkedin merdouille
- [x] Largeur : on n'utilise pas la même largeur pour tous les composants de la page (cf. la section "Initiation, ressources ... " et la suite)
- [x] + la partie haute semble aussi décalée
Bref éviter à l'oeil d'avoir à faire des vagues
- [x] "Ressources" pointe vers une section "Bibliothèque" qui référence des "ressources". Confirmer qu'on garde bien ce terme
- [x] "déc." pourquoi ne pas mettre "décembre" ?
- [x] Le lien vers la méthodologie amène en milieu de page et pas en haut comme attendu

**Comment by annelhote** [comment]
Le partage de LinkedIn ne fonctionnera qu'une fois en prod en raison de l'authentification demandée sur le site de staging.

**Comment by annelhote** [comment]
On écrit "déc." et non "décembre" pour des soucis de place. Cette pastille n'est pas très grande...

**Comment by annelhote** [comment]
Je n'arrive pas à reproduire ce bug : "Le lien vers la méthodologie amène en milieu de page et pas en haut comme attendu"
