### ISSUE TITLE
EN - Home  Header Footer 

### ISSUE THREAD

**Issue by Jojooct10** [dataesr/bso-ui#266]
- [x] Lien vers PNSO 2 en version EN https://www.enseignementsup-recherche.gouv.fr/sites/default/files/2021-10/2e-plan-national-pour-la-science-ouverte-version-anglaise--13715.pdf
- [x] Lien vers licence Etalab 2. Je mettrais https://github.com/etalab/licence-ouverte/blob/master/open-licence.md . Non ?
- [x] la "devise" de scanR en anglais me semble un peu naze. Peut êtres'écarter de la traduction française pour un truc comme : "scanR, search french research and innovation ecosystem" ?
- [x] le sous-titre du BSO me semble uniquement lié aux publications (vaut aussi pour FR bien sûr). "The French Open science Monitor. Measuring the evolution of **open access to publications** in France from reliable, open and controlled data". L'adapter ?
- [x] pourquoi a t on cela dans la version EN
![image](https://user-images.githubusercontent.com/34550712/150969305-44921184-b33d-4bb9-b315-547a4586eed3.png)

**Comment by annelhote** [comment]
OK
