### ISSUE TITLE
Ajouter un graphique du taux d'ouverture par type de publications

### ISSUE THREAD

**Issue by ericjeangirard** [dataesr/bso-ui#305]
Pas seulement sur la dernière année de publication, mais sur tout l'historique depuis 2013

**Comment by annelhote** [comment]
https://bso.staging.dataesr.ovh/integration/fr/publi.general.genres-ouverture.chart-evolution-proportion

**Comment by ericjeangirard** [comment]
En prod https://barometredelascienceouverte.esr.gouv.fr/integration/fr/publi.general.genres-ouverture.chart-evolution-proportion le graphique ne devrait pas aller jusqu'en 2022, mais s'arrêter en 2021 (dynamiquement par rapport à la lastObservationDate)
