### ISSUE TITLE
Module de constitution d'une liste de publications

### ISSUE THREAD

**Issue by ericjeangirard** [dataesr/bso-ui#307]
Pour l'étape 1 des BSO locaux
Input utilisateur : 
- Une liste de requêtes d'affiliation
Ex d'1 requête: ( Ingénierie-Biologie-Santé Lorraine OR UMS 2008 OR IBSLor OR IBSLOR OR UMS2008 OR UMS CNRS 2008 ) 
Pays:  (France)
Ville:  (METZ* OR NANCY* OR EPINAL* OR COSNES* OR  St Die* OR Saint die* OR Longwy* OR St Avold OR Saint Avold OR Saint-Avold OR Vandoeuvre OR St Avoid OR Lorraine OR Saulcy OR Villers OR YUTZ OR Champenoux OR Seichamps OR Chavigny OR MAX VILLE OR LAXOU)

- Potentiellement une liste de nom / prénom d'auteur
- Une année ?

==> l'outil interroge l'API BSO (et potentiellement) l'API OpenAlex

==> restitue les publications trouvée dans un tableau paginé

en mettant en évidence ce qu'il a trouvé

UI pour valider / invalider en masser ce qui a été trouvé (toutes les publis avec la même affiliation par ex)

Export Excel

Dans la V2
Suggestion d'identifiant avec l'affiliation-matcher
Enregistrement des identifiants affiliation et auteur

Module assez générique, peut etre devrait etre hors BSO ?

**Comment by ericjeangirard** [comment]
@ericjeangirard @annelhote préparer une requête ES avec
- affiliations à inclure / à exlcure
- noms / prénoms
- année ?

**Comment by annelhote** [comment]
I close it because it has been done thanks here https://github.com/dataesr/works-finder/
