### ISSUE TITLE
Support of ODS format for requestion a local monitor

### ISSUE THREAD

**Issue by annelhote** [dataesr/bso-ui#308]
Libre Office format. Might be supported by the xxlsx node module ?

**Comment by GGre** [comment]
Intérêt d'intégrer ce format :
J'ai récemment mis au point une recette afin que les laboratoires puissent eux-mêmes décliner aussi simplement que possible le BSO :
https://git.unistra.fr/gressot/bso_labo

Pratiquement, les usagers manipulent les données csv dans des tableurs et non dans un simple fichier texte. Du coup, le passage au format csv requiert presque à tout coup une étape de conversion en csv.
Actuellement cette étape n'est pas nécessaire si le tableur est Excel ; elle l'est si le tableur est Libre Office.
Cela se traduit dans ma recette :
https://git.unistra.fr/gressot/bso_labo/-/blob/main/7_all_in_one.md?ref_type=heads#set-your-final-file
où je dois préciser :
> If your file is a .xls you don't have to change it in a .csv ; if your file is a .odt, save it as a .csv

Une étape de moins, cela peut avoir l'air de peu de chose mais c'est beaucoup. Pour moi le BSO c'est l'ouverture des données, du code, l'utilisation de logiciels et de licences libres (comme etalab) : il serait donc dommage que le BSO promeuve Excel aux dépens de Libre Office.
