### ISSUE TITLE
Pastille date de mise à jour

### ISSUE THREAD

**Issue by ericjeangirard** [dataesr/bso-ui#62]
Les données sont dynamiques et récupérables à partir de l'api sur l"index bso-publications.

1) Il faut d'abord récupérer les observation_dates
POST "https://cluster.elasticsearch.dataesr.ovh/bso-publications/_search"
{
  "size": 0,
  "aggs" : {
    "observation_dates" : {
      "terms" : { "field": "observation_dates.keyword" }
    }
  }
}

donne par exemple 
[{'key': '2021Q1', 'doc_count': 343182},
    {'key': '2020', 'doc_count': 320939},
    {'key': '2019', 'doc_count': 274529},
    {'key': '2018', 'doc_count': 221492}]

=> la dernière date d'observation est 2021Q1.
=> la dernière année d'observation est 2021.
=> donc on prend en compte les données de publications de 2013 (fixé) à 2020 (=2021 - 1)
Pour avoir la date de mise à jour, c'est une nouvelle requête avec
{
  "size": 0,
  "aggs" : {
    "observation_dates" : {
      "terms" : { "field": "oa_details.LAST_OBS_DATE.snapshot_date.keyword" }
    }
  }
}
en remplacant LAST_OBS_DATE par la dernière date d'observation.
On obtient {'key': '20210307', 'doc_count': 343182}
et la date est donc 2021-03-07.

**Comment by francasix** [comment]
@ericjeangirard À quel moment on ajoute le filtre santé dans la requête ?

**Comment by ericjeangirard** [comment]
pour le coup il n'y a pas de filtre santé, toute la base des publis sera mise à jour en même temps (santé ou pas) (en faisant abstraction des essais cliniques)

**Comment by ericjeangirard** [comment]
En fait pour le startDate, là il affiche 2018 (https://github.com/dataesr/bso-ui/commit/edabc586fa48a29ddf9fa18af34f1dcf0bc3e0b6#diff-8f356d1d15e6f923f60377bd9f373219479a2b0e89b068480062ddfafdef7b31R21 )
2018 c'est la 1ère date d'observation, mais dans cette phrase c'est la première date de publication qui nous intéresse.
malheureusement, dans les données il y peut y avoir des publications antérieures, mais c'est complet à partir de 2013.

et donc c'est 2013 qu'il faut afficher (on peut le hardcoder je pense ?)

**Comment by ericjeangirard** [comment]
et en mettant à jour l'index (il y a une nouvelle date d'observation 2021Q2), il affiche
"Site mis à jour le 7 mars 2021 avec les données de 2018 à 2021Q1"
mais il devrait afficher
"Site mis à jour le **2 juin 2021** avec les données de **2013** à **2021**"

l'info du 2 juin vient du champ snapshot_date pour la dernière date d'observation
