### ISSUE TITLE
Cards pour la page Publications sur la baromètre santé

### ISSUE THREAD

**Issue by annelhote** [dataesr/bso-ui#87]
<img width="734" alt="Screenshot 2021-08-05 at 11 00 29" src="https://user-images.githubusercontent.com/11627007/128324395-988ae523-f174-4c19-ae7d-418da1a86ce3.png">

**Comment by annelhote** [comment]
* des publications françaises en santé sont ouvertes dans le millésime 2020
* Dépenses estimées pour la communauté scientifique, en APC pour la production en santé
* des publications en santé ouvertes sont en “diamond”
* documents en santé hébergés sur XXX, en tête des archives ouvertes en nombre de publications hébergées
* des publications en santé ouvertes sont en langue française
* est le pays d’origine des auteurs de rang utile avec lesquels la France collabore le plus

**Comment by annelhote** [comment]
Requête ES :

**Comment by annelhote** [comment]
Résultats :
1.  response["aggregations"]["by_is_oa"]["buckets"][key == 1]["doc_count"] / response["aggregations"]["count_publications"]["value"] * 100
2. response["aggregations"]["sum_apc"]["value"]
3. response["aggregations"]["by_oa_colors"]["buckets"][key == "diamond"]["doc_count"] / response["aggregations"]["count_publications"]["value"] * 100
4.
5.
6.

**Comment by poplingue** [comment]
![Uploading Screenshot 2021-08-05 at 11.00.29.png…]()

**Comment by poplingue** [comment]
<img width="734" alt="Screenshot 2021-08-05 at 11 00 29" src="https://user-images.githubusercontent.com/11627007/128324332-00986f00-ea08-47cc-84bd-cf5d51ab083b.png">

**Comment by poplingue** [comment]
@annelhote le `total_publications` c'est bien 
```
"count_publications": {
      "value": 303106
    },
```
dans le résultat de la requête ?
